module

public import Paper.ATAlgebra
public import Paper.ATApproximation
public import Paper.ATCoordinates
public import Paper.ATCurve
public import Paper.ATGraph
public import Paper.ATImplicit
public import Paper.ATSmoothGraph
public import Paper.BCFTranslation
public import Paper.BoundedHeatGradientContinuity
public import Paper.BoundedHeatSourceAudit
public import Paper.BoundedHeatSourceRegularity
public import Paper.CanonicalBrownian
public import Paper.ConditionalMain
public import Paper.ControlCostIntegrability
public import Paper.DerivativeCompactness
public import Paper.DiracBrownianState
public import Paper.DiracClassicalRegularity
public import Paper.DiracClassicalRegularityAudit
public import Paper.DiracConditionalLaw
public import Paper.DiracItoState
public import Paper.DiracLawIdentification
public import Paper.DiracMagnetization
public import Paper.DiracShift
public import Paper.DiracSoftConditional
public import Paper.DiracSoftConditionalAudit
public import Paper.DiracSoftMoment
public import Paper.DiracState
public import Paper.DiracStateLaw
public import Paper.DoobDifferentiation
public import Paper.DoobFourier
public import Paper.DoobHeat
public import Paper.DoobKernel
public import Paper.FiniteContinuity
public import Paper.FiniteSK
public import Paper.FixedPoint
public import Paper.FixedPointUnique
public import Paper.FourierMeasure
public import Paper.Gaussian
public import Paper.GaussianAppendixIdentities
public import Paper.GaussianBoundedSmoothing
public import Paper.GaussianConvolution
public import Paper.GaussianCurveSigns
public import Paper.GaussianDifferentiation
public import Paper.GaussianHeat
public import Paper.GaussianIBP
public import Paper.GaussianMean
public import Paper.GaussianPoincare
public import Paper.GaussianPoincareStrict
public import Paper.GaussianPositivity
public import Paper.GaussianSmooth
public import Paper.HJBControlCost
public import Paper.HJBEndpoint
public import Paper.HJBGrid
public import Paper.HJBGridCells
public import Paper.HJBGridCellsAudit
public import Paper.HJBGridTelescope
public import Paper.HJBOptimal
public import Paper.HJBTimeGrid
public import Paper.HJBTimePotentialLimit
public import Paper.HJBVerification
public import Paper.HeatAdjoint
public import Paper.HeatContraction
public import Paper.HeatGradient
public import Paper.HeatGrowth
public import Paper.HeatMaximum
public import Paper.HeatSourceCongruence
public import Paper.HeatTest
public import Paper.Hyperbolic
public import Paper.ItoExpectation
public import Paper.ItoLeftSums
public import Paper.ItoStateIntegrability
public import Paper.JTFubini
public import Paper.JTVariational
public import Paper.MainExtension
public import Paper.MomentBridge
public import Paper.MomentEndpoints
public import Paper.MomentExponential
public import Paper.MomentIntegral
public import Paper.NumberedResults
public import Paper.NumberedResultsAudit
public import Paper.PDEFixedPoint
public import Paper.ParisiBrownianState
public import Paper.ParisiCDFGrid
public import Paper.ParisiCDFIntegral
public import Paper.ParisiControlConvexity
public import Paper.ParisiControlDerivative
public import Paper.ParisiControlEnvelope
public import Paper.ParisiControlFirstVariation
public import Paper.ParisiControlStability
public import Paper.ParisiControlledState
public import Paper.ParisiCorrectionStability
public import Paper.ParisiCurvature
public import Paper.ParisiDiracIdentification
public import Paper.ParisiDiracIdentificationAudit
public import Paper.ParisiDuhamelWeak
public import Paper.ParisiFiniteApproximation
public import Paper.ParisiFiniteCells
public import Paper.ParisiFiniteGlue
public import Paper.ParisiFiniteGradientTime
public import Paper.ParisiFiniteMild
public import Paper.ParisiFiniteSpatial
public import Paper.ParisiFiniteStep
public import Paper.ParisiFirstVariation
public import Paper.ParisiGlobalApproximation
public import Paper.ParisiGradientCells
public import Paper.ParisiGradientGrid
public import Paper.ParisiGradientMartingale
public import Paper.ParisiGradientMartingaleLaw
public import Paper.ParisiGradientMesh
public import Paper.ParisiGradientTerminalPairing
public import Paper.ParisiGridCDF
public import Paper.ParisiGridScheme
public import Paper.ParisiGridStability
public import Paper.ParisiHJB
public import Paper.ParisiHJBBase
public import Paper.ParisiHJBFeedback
public import Paper.ParisiHJBLimit
public import Paper.ParisiHJBTime
public import Paper.ParisiHJBValueFunction
public import Paper.ParisiItoState
public import Paper.ParisiJT
public import Paper.ParisiJTFoundation
public import Paper.ParisiLocal
public import Paper.ParisiMeasureStability
public import Paper.ParisiMild
public import Paper.ParisiMildDerivative
public import Paper.ParisiMildUnique
public import Paper.ParisiMixContinuity
public import Paper.ParisiMixConvexity
public import Paper.ParisiMixDifferentiation
public import Paper.ParisiMixGlobalDifferentiation
public import Paper.ParisiMixTerminalDifferentiation
public import Paper.ParisiPDE
public import Paper.ParisiPDEFormula
public import Paper.ParisiPDEFormulaAudit
public import Paper.ParisiPDEWellPosed
public import Paper.ParisiPotentialStability
public import Paper.ParisiPotentialVariation
public import Paper.ParisiRestartState
public import Paper.ParisiSchemeMeasure
public import Paper.ParisiSchemeMild
public import Paper.ParisiSelectedGFubini
public import Paper.ParisiSelectedMoment
public import Paper.ParisiSelectedState
public import Paper.ParisiSlabMild
public import Paper.ParisiSolution
public import Paper.ParisiSolutionSlabs
public import Paper.ParisiSolutionUniqueness
public import Paper.ParisiSpatialBounds
public import Paper.ParisiSpatialSmooth
public import Paper.ParisiState
public import Paper.ParisiStateShift
public import Paper.ParisiStateStability
public import Paper.ParisiTerminalOperator
public import Paper.ParisiTerminalStability
public import Paper.ParisiTerminalWeak
public import Paper.ParisiTestRegularity
public import Paper.ParisiTimeRegularity
public import Paper.ParisiTimeShiftTest
public import Paper.ParisiTranslation
public import Paper.ParisiVariation
public import Paper.ParisiWeak
public import Paper.ParisiWeakLipschitz
public import Paper.ParisiWeakMild
public import Paper.ParisiWeakPotentialSpace
public import Paper.ParisiWeakRecovery
public import Paper.ParisiWeakRegularRecovery
public import Paper.ParisiWeakRepresentative
public import Paper.ParisiWeakSelected
public import Paper.ParisiWeakUniqueness
public import Paper.ParisiWeakWellPosed
public import Paper.ParisiWeightedVolterra
public import Paper.PhysicalMoments
public import Paper.PhysicalParisiFormula
public import Paper.PhysicalSKBridge
public import Paper.PhysicalSKDisorder
public import Paper.QuadraticImplicit
public import Paper.RSContinuity
public import Paper.RSFunctional
public import Paper.RSMoments
public import Paper.RSSoft
public import Paper.ReplicaSymmetry
public import Paper.SKBackendParameters
public import Paper.Semigroup
public import Paper.SoftMoment
public import Paper.SoftMomentStrict
public import Paper.StateDiffusion
public import Paper.StrictRSMoments
public import Paper.Structural
public import Paper.SymmetrizedWeight
public import Paper.TanhPolynomial
public import Paper.Targets
public import Paper.Variational
public import Paper.VolterraFubini
public import Paper.WeakHeatMollification
public import Paper.WeakHeatUniqueness
public import Paper.WeightedDrift

@[expose] public section

/-!
# Formalization of arXiv:2604.11921v2

This aggregate imports every project module, the fifteen closed numbered
results, and all concrete physical, Gaussian, PDE, stochastic, and variational
foundations. The exact correspondence and source inventory are recorded in
COVERAGE.md and results.json. Rejecting axiom checks are included and the
independent complete audit is provided by tools/audit.py.
-/
